
name: Hello World


on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compile the file
        run: gcc .\EV_program.c

      - name: execute the file
        run: .\a.exe
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifact_file
          path: a.exe
          
      - name: Uploading Artifacts on Jfrog
        run: curl -H "X-JFrog-Art-Api:AKCp8nHPRK7xGZFNVyoT89egKdUSnKSiTmmQmQZTAkcw2jYH861Hgb4hkBN2bYvrjTPRNLRhr" -T a.exe "https://nikhil28cs.jfrog.io/artifactory/example-repo-local/"         
          
        
  release:
    runs-on: self-hosted
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#       - name: Download a Build Artifact from Github
#         uses: actions/download-artifact@v3.0.1
#         with:
#           # Artifact name
#           name: Artifact_file
          
      - name: Download a Build Artifact from Jfrog
        run: curl.exe -H "X-JFrog-Art-Api:AKCp8nHPRK7xGZFNVyoT89egKdUSnKSiTmmQmQZTAkcw2jYH861Hgb4hkBN2bYvrjTPRNLRhr" -O "https://nikhil28cs.jfrog.io/artifactory/example-repo-local/a.exe"        

        
      - name: Run the artifact
        run: .\a.exe
        
        
        
          

