
name: Hello World


on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compile the file
        run: gcc EV_program.c

      # Runs docker hello-world
      - name: execute the file
        run: ./a.out
        
#   execute:
#     runs-on: self-hosted

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Download the artifacts
#         run: echo Hello, world!

#       - name: Execute the file
#         run: docker run hello-world
